spring:
  application:
    name: Organizados

  datasource:
    url: jdbc:postgresql://localhost:5432/organizados_db
    username: postgres
    password: Gold20050404!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect